### ISSUE TITLE
WorldExplorer 0.0.3: Justice League Heroes - Flipped Normals?

### ISSUE THREAD

**Issue by 0Curtain0** [bigianb/bgda-explorer#11]
**WorldExplorer v0.0.3** 
**Operating System:** Windows 7 64bit (Virtual Machine) 

I've seen this happen in previous versions of WorldExplorer as well, but I figured I should report it. 
The exported OBJs appears to have random faces/normals that are flipped. 
- https://gfycat.com/nippygrayeeve 

---------------

**Off topic:** 
Before I forget, does  exporting the **Posed** model export the character and its pose from the active frame in a selected animation (**.anm**) file? I haven't experimented with it yet.

In regards to the missing hair, that will be fixable in the future java based export tool?

**Comment by bigianb** [comment]
The normals should be okay .... but the faces winding order is often wrong. The issue here is that the PS2 does not do backface culling (or at least the snowblind engine does not) and so we find that the winding order is not consistent. I try to fix this in the export by looking at the normal ... but it's not always possible.

The posed model export uses the current animation frame and exports the mesh deformed according to that. So ... in short I think the answer is 'yes'.

Does the model have hair? I just assumed that was hidden by the tophat. There are some unknown VU routines in the JLH models that I will need to look into more in the future.

**Comment by bigianb** [comment]
see #3
